-- CreateTable
CREATE TABLE "Widget" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),

    CONSTRAINT "Widget_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TradingPair" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "date" TIMESTAMP(3) NOT NULL,
    "open" FLOAT8 NOT NULL,
    "high" FLOAT8 NOT NULL,
    "low" FLOAT8 NOT NULL,
    "close" FLOAT8 NOT NULL,

    CONSTRAINT "TradingPair_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Market" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "price" FLOAT8 NOT NULL,
    "change" FLOAT8 NOT NULL,

    CONSTRAINT "Market_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" STRING NOT NULL,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "OrderBook" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "symbol" STRING NOT NULL,
    "bidPrice" FLOAT8 NOT NULL,
    "askPrice" FLOAT8 NOT NULL,
    "bidQuantity" FLOAT8 NOT NULL,
    "askQuantity" FLOAT8 NOT NULL,
    "userId" INT4 NOT NULL,

    CONSTRAINT "OrderBook_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Wallet" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "currency" STRING NOT NULL,
    "balance" FLOAT8 NOT NULL,
    "userId" INT4 NOT NULL,

    CONSTRAINT "Wallet_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "OrderBook" ADD CONSTRAINT "OrderBook_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Wallet" ADD CONSTRAINT "Wallet_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
